### ISSUE TITLE
Needs Spam Handling Procedure Defined

### ISSUE THREAD

**Issue by andrewbolster** [nitechdesign/code-of-conduct#12]
Currently no agreed spam handling procedure defined or agreed.

**Comment by mauricerkelly** [comment]
This is what I have historically done:

- directly message a _suspected_ spammer saying something along the lines of "This group operates a no-spam policy, and some of your messages to date seem to qualify to us as spam. Please remove the messages within X hours, or I will delete them myself. Further posting of messages that appear to be spam will result in your account being deactivated."
- post a message in the affected rooms to say that the spammer has been contacted
- await response
- if no response, delete the messages
- if a response, and messages are deleted, thank the spammer
- if spammer repeats the offence send a message saying something along the lines of "you were warned, and you did it again. Your account will now be deleted." (doesn't matter if they deleted their original messages or not when asked - the key thing is that they ignored the request to not do it again)
- deactivate their account.

I think this works, because it promotes dialogue and allows for some wiggle room on the definition of spam. I don't like insta-deletion because it comes across as heavy-handed.

With multiple admins, my suggestion for improvement here only amount to keeping other admins informed - let the other admins know that you are handling things and keep them updated. That way the offender is only being addressed by one admin.

Of course, that detail does not necessarily belong in the Code of Conduct. For the Code of Conduct itself, I think we need to loosely define what we consider to be spam (or spammy behaviour), express that we have a 2-strikes-and-out rule, and that there is an expectation to delete, or have your spam messages deleted.

**Comment by andrewbolster** [comment]
Resolved by #22
