### ISSUE TITLE
Explicitly state the scope of the CoC

### ISSUE THREAD

**Issue by mauricerkelly** [nitechdesign/code-of-conduct#8]
<img width="683" alt="screenshot of slack 22-02-2018 11-39-05" src="https://user-images.githubusercontent.com/729402/36536517-1d968154-17c5-11e8-8a33-8d3bad93e055.png">

**Comment by mauricerkelly** [comment]
In retrospect, I'm not as convinced about this suggestion. This could lead to people creating channels with their own rules - at some point they may feel that someone is contravening their rules and expect the admins to remove that person.

I think it's a tough enough prospect to maintain a single set of rules across the entire Slack, without bringing the enforcement of custom rules into the mix.

(The only thing I think is different is #jobs - but while the channel has "rules", nothing is enforced other than by gentle shaming of violators - e.g. not including traybake policy in job postings)

Any opinions?

**Comment by andrewbolster** [comment]
"The best thing about standards is there's so many to choose from"

I'd agree with the concern about getting overly prescriptive of scope and creating the possibility of 'pocket-slacks' with different rules. 

IMO, KISS and state that the CoC applies cross-slack and while there may be community conventions within individual slacks, they do not supersede or otherwise undermine the CoC
